In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [6]:
spam_df=pd.read_csv(r"D:\AI\Machine_Learning\supervised_learning\spam.csv")

In [14]:
spam_df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [13]:
#inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [16]:
#turning spam/ham into numerical data, create new column call spam
def label(s):  # or using lambda: spam_df['spam']=spam_df['Category'].apply(lambda x: 1 if x=='spam' else 0)
    if s=='spam':
        return 1
    else:
        return 0
spam_df['Spam_label']=spam_df['Category'].apply(label)

In [24]:
X=spam_df['Message']
y=spam_df['Spam_label']

In [79]:
#train/test split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [80]:
X_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...                        
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: Message, Length: 4457, dtype: object

In [83]:
#Find word count and store data as a matrix
cv=CountVectorizer()  #feature extraction on text data. Converts a collection text document into a matrix of token(word) counts [0;1]. That mean count number of each words that repeat in each document
X_train_count=cv.fit_transform(X_train.values)

In [82]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [84]:
model=MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [85]:
#pre-test ham
email_ham=["hey wanna play footbal?"]
email_ham_count=cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [86]:
#pre-test spam
email_spam=["reward money click"]
email_spam_count=cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [87]:
from sklearn.metrics import accuracy_score

In [91]:
#test model
X_test_count=cv.transform(X_test)
y_pred=model.predict(X_test_count)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [92]:
#evaluate
evaluate=accuracy_score(y_test,y_pred)
evaluate

0.9919282511210762